###

POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

    {
        "firstName": "bob",
        "lastName": "john",
        "email": "test@das.com",
        "password": "abc123"
        
    }